In [10]:
import numpy as np
import polars as pl
import polars.selectors as cs
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import great_tables as tg
import altair as alt

In [11]:
df_path = r'../DATASETS/Data_cancer.csv'

In [14]:
df = pl.read_csv(df_path)

In [16]:
df

shape: (683, 11)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬─────────┬───────┐
│ Sample     ┆ Clump      ┆ Uniformity ┆ Uniformity ┆ … ┆ Bland      ┆ Normal    ┆ Mitoses ┆ Class │
│ code       ┆ Thickness  ┆ of Cell    ┆ of Cell    ┆   ┆ Chromatin  ┆ Nucleoli  ┆ ---     ┆ ---   │
│ number     ┆ ---        ┆ Size       ┆ Shape      ┆   ┆ ---        ┆ ---       ┆ i64     ┆ i64   │
│ ---        ┆ i64        ┆ ---        ┆ ---        ┆   ┆ i64        ┆ i64       ┆         ┆       │
│ i64        ┆            ┆ i64        ┆ i64        ┆   ┆            ┆           ┆         ┆       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═════════╪═══════╡
│ 1000025    ┆ 5          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1002945    ┆ 5          ┆ 4          ┆ 4          ┆ … ┆ 3          ┆ 2         ┆ 1       ┆ 2     │
│ 1015425    ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ 1016277    ┆ 6          ┆ 8          ┆ 8          ┆ … ┆ 3          ┆ 7         ┆ 1       ┆ 2     │
│ 1017023    ┆ 4          ┆ 1          ┆ 1          ┆ … ┆ 3          ┆ 1         ┆ 1       ┆ 2     │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …       ┆ …     │
│ 776715     ┆ 3          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 841769     ┆ 2          ┆ 1          ┆ 1          ┆ … ┆ 1          ┆ 1         ┆ 1       ┆ 2     │
│ 888820     ┆ 5          ┆ 10         ┆ 10         ┆ … ┆ 8          ┆ 10        ┆ 2       ┆ 4     │
│ 897471     ┆ 4          ┆ 8          ┆ 6          ┆ … ┆ 10         ┆ 6         ┆ 1       ┆ 4     │
│ 897471     ┆ 4          ┆ 8          ┆ 8          ┆ … ┆ 10         ┆ 4         ┆ 1       ┆ 4     │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴─────────┴───────┘

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X = df.select(cs.exclude('Class'))

In [19]:
y = df['Class']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()

In [23]:
scaled_X_train = scaler.fit_transform(X_train)

In [24]:
scaled_X_test = scaler.transform(X_test)

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
logistic_regression = LogisticRegression()

In [27]:
logistic_regression.fit(scaled_X_train, y_train)

LogisticRegression()

In [28]:
predictions = logistic_regression.predict(scaled_X_test)

In [29]:
predictions

array([4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 4, 4, 2,
       4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 2, 4, 4, 2, 4, 4, 2,
       2, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2,
       4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2,
       4, 4, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2])

In [43]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [44]:
print(accuracy_score(y_test, predictions))
confusion_matrix(y_test, predictions)

0.9532163742690059


array([[102,   1],
       [  7,  61]])

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn_classifier = KNeighborsClassifier()

In [34]:
knn_classifier.fit(scaled_X_train, y_train)

KNeighborsClassifier()

In [35]:
knn_predictions = knn_classifier.predict(scaled_X_test)

In [45]:
print(accuracy_score(y_test, knn_predictions))
confusion_matrix(y_test, knn_predictions)

0.9532163742690059


array([[102,   1],
       [  7,  61]])

In [37]:
from sklearn.svm import SVC

In [38]:
svc_model = SVC()

In [40]:
svc_model.fit(scaled_X_train, y_train)

SVC()

In [41]:
svc_predictions = svc_model.predict(scaled_X_test)

In [46]:
print(accuracy_score(y_test, svc_predictions))
confusion_matrix(y_test, svc_predictions)

0.9532163742690059


array([[100,   3],
       [  5,  63]])

In [48]:
svc_model_linear = SVC(kernel='linear')

In [49]:
svc_model_linear.fit(scaled_X_train, y_train)

SVC(kernel='linear')

In [50]:
svc_model_linear_predictions = svc_model_linear.predict(scaled_X_test)

In [52]:
print(accuracy_score(y_test, svc_model_linear_predictions))
confusion_matrix(y_test, svc_model_linear_predictions)

0.9532163742690059


array([[102,   1],
       [  7,  61]])

In [53]:
from sklearn.naive_bayes import GaussianNB

In [54]:
gaussian_nb = GaussianNB()

In [55]:
gaussian_nb.fit(scaled_X_train, y_train)

GaussianNB()

In [56]:
gaussian_nb_predictions = gaussian_nb.predict(scaled_X_test)

In [57]:
print(accuracy_score(y_test, gaussian_nb_predictions))
confusion_matrix(y_test, gaussian_nb_predictions)

0.9649122807017544


array([[100,   3],
       [  3,  65]])

In [58]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
decision_tree = DecisionTreeClassifier()

In [61]:
decision_tree.fit(scaled_X_train, y_train)

DecisionTreeClassifier()

In [62]:
decision_tree_predictions = decision_tree.predict(scaled_X_test)

In [63]:
print(accuracy_score(y_test, decision_tree_predictions))
confusion_matrix(y_test, decision_tree_predictions)

0.9532163742690059


array([[102,   1],
       [  7,  61]])

In [64]:
from sklearn.ensemble import RandomForestClassifier

In [65]:
random_forest = RandomForestClassifier()

In [66]:
random_forest.fit(scaled_X_train, y_train)

RandomForestClassifier()

In [67]:
random_forest_predictions = random_forest.predict(scaled_X_test)

In [68]:
print(accuracy_score(y_test, random_forest_predictions))
confusion_matrix(y_test, random_forest_predictions)

0.9473684210526315


array([[102,   1],
       [  8,  60]])